import { Inter } from "next/font/google";
import "../styles/globals.css"; // Adjust the path to ensure it's correct

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "flight-booking",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add metadata for SEO */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* You can add more meta tags here if needed */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
